BAIZE_REPO_NAME = "BaiZeNote"
NOTEBOOKS_REPO_LOCATION_KEY = "NOTE_BOOKS_REPO_PATH_FULL"

STANDARD_SERVER_MODE = "-server"
REPOSITORY_SERVER_MODE = "-rserver"
STANDARD_LOCAL_MODE = "-local"
REPOSITORY_LOCAL_MODE = "-rlocal"
