import os
from pathlib import Path

PATH_FULL_SYS_LOCATION = Path(Path(os.path.dirname(__file__)).parent).parent

PATH_RELA_NOTEBOOKS_RES_LOCATION_JSON = "configs/note_books_resource.json"
PATH_FULL_NOTEBOOKS_RES_LOCATION_JSON = os.path.join(PATH_FULL_SYS_LOCATION, PATH_RELA_NOTEBOOKS_RES_LOCATION_JSON)

PATH_RELA_NOTEBOOKS_DEST_LOCATION_JSON = "configs/note_books_destination.json"
PATH_FULL_NOTEBOOKS_DEST_LOCATION_JSON = os.path.join(PATH_FULL_SYS_LOCATION, PATH_RELA_NOTEBOOKS_DEST_LOCATION_JSON)

PATH_RELA_NOTEBOOKS_THEME_JSON = "configs/note_books_themes.json"
PATH_FULL_NOTEBOOKS_THEME_JSON = os.path.join(PATH_FULL_SYS_LOCATION, PATH_RELA_NOTEBOOKS_THEME_JSON)
